// Package xcode provides utilities for Xcode configuration management.
package xcode

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/undrift/drift/internal/supabase"
)

// XcconfigGenerator generates Xcode configuration files.
type XcconfigGenerator struct {
	OutputPath     string
	BuildServerDir string
}

// NewXcconfigGenerator creates a new xcconfig generator.
func NewXcconfigGenerator(outputPath string) *XcconfigGenerator {
	return &XcconfigGenerator{
		OutputPath:     outputPath,
		BuildServerDir: filepath.Dir(outputPath),
	}
}

// XcconfigData holds the data for xcconfig generation.
type XcconfigData struct {
	GitBranch       string
	Environment     string
	SupabaseBranch  string
	ProjectRef      string
	APIURL          string
	AnonKey         string
	IsFallback      bool
	GeneratedAt     time.Time
}

const xcconfigTemplate = `// Config.xcconfig
// Auto-generated by drift - DO NOT EDIT
// Generated: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}
// Git Branch: {{.GitBranch}}
// Environment: {{.Environment}}
{{if .IsFallback}}// NOTE: Using fallback - no Supabase branch for this git branch{{end}}

// Supabase Configuration
SUPABASE_URL = {{.APIURL}}
SUPABASE_ANON_KEY = {{.AnonKey}}
SUPABASE_PROJECT_REF = {{.ProjectRef}}

// Environment
DRIFT_ENVIRONMENT = {{.Environment}}
DRIFT_GIT_BRANCH = {{.GitBranch}}
DRIFT_SUPABASE_BRANCH = {{.SupabaseBranch}}
`

// Generate generates the Config.xcconfig file.
func (g *XcconfigGenerator) Generate(data XcconfigData) error {
	tmpl, err := template.New("xcconfig").Parse(xcconfigTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	// Ensure directory exists
	dir := filepath.Dir(g.OutputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Create output file
	f, err := os.Create(g.OutputPath)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	// Execute template
	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to write xcconfig: %w", err)
	}

	return nil
}

// GenerateFromBranchInfo generates xcconfig from Supabase branch info.
func (g *XcconfigGenerator) GenerateFromBranchInfo(info *supabase.BranchInfo, anonKey string) error {
	data := XcconfigData{
		GitBranch:      info.GitBranch,
		Environment:    string(info.Environment),
		SupabaseBranch: info.SupabaseBranch.Name,
		ProjectRef:     info.ProjectRef,
		APIURL:         info.APIURL,
		AnonKey:        anonKey,
		IsFallback:     info.IsFallback,
		GeneratedAt:    time.Now(),
	}

	return g.Generate(data)
}

// GenerateBuildServerJSON generates the buildServer.json for sourcekit-lsp.
func (g *XcconfigGenerator) GenerateBuildServerJSON(xcodeProjectPath, scheme string) error {
	buildServerPath := filepath.Join(g.BuildServerDir, "buildServer.json")

	// Find the .xcodeproj or .xcworkspace
	projectFile := xcodeProjectPath
	if projectFile == "" {
		// Try to find it
		matches, _ := filepath.Glob(filepath.Join(g.BuildServerDir, "*.xcworkspace"))
		if len(matches) > 0 {
			projectFile = matches[0]
		} else {
			matches, _ = filepath.Glob(filepath.Join(g.BuildServerDir, "*.xcodeproj"))
			if len(matches) > 0 {
				projectFile = matches[0]
			}
		}
	}

	if projectFile == "" {
		return fmt.Errorf("no Xcode project found")
	}

	content := fmt.Sprintf(`{
  "name": "xcode build server",
  "version": "0.2",
  "bspVersion": "2.0",
  "languages": ["swift", "objective-c", "objective-cpp", "c", "cpp"],
  "argv": [
    "/Applications/Xcode.app/Contents/Developer/usr/bin/xcode-build-server"
  ],
  "build_root": "%s",
  "workspace": "%s",
  "scheme": "%s"
}
`, g.BuildServerDir, projectFile, scheme)

	return os.WriteFile(buildServerPath, []byte(content), 0644)
}

// ReadXcconfig reads an existing xcconfig file and returns its values as a map.
func ReadXcconfig(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	values := make(map[string]string)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		
		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}

		// Parse KEY = VALUE
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			values[key] = value
		}
	}

	return values, nil
}

// GetCurrentEnvironment reads the current environment from the xcconfig.
func GetCurrentEnvironment(xcconfigPath string) (string, error) {
	values, err := ReadXcconfig(xcconfigPath)
	if err != nil {
		return "", err
	}

	if env, ok := values["DRIFT_ENVIRONMENT"]; ok {
		return env, nil
	}

	return "", fmt.Errorf("DRIFT_ENVIRONMENT not found in %s", xcconfigPath)
}

// XcconfigExists checks if the xcconfig file exists.
func XcconfigExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

